In [1]:
%run numpy_intro.py

In [2]:
prob1()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [3]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
prob3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

In [5]:
prob4([-3,-1,3])

array([0, 0, 3])

In [6]:
prob5()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [7]:
A = np.array([[1,1,0],[0,1,0],[1,1,1]])
prob6(A)

array([[0.5       , 0.5       , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333]])

In [8]:
prob7()

np.int64(70600674)