In [4]:
import numpy as np
from scipy import linalg as la

In [65]:
A = np.array([-1,1,2,3,4,5,6,7,8]).reshape((3,3))
#A = 2*np.array([0,1,1,0]).reshape((2,2))
A = np.array([0, 1, 1, 0]).reshape((2,2)) # line from a to b
A = np.array([0, 1, 1, 1, 0, 1, 1,1, 0]).reshape((3,3)) #connected triangle
A = np.array([0, 1, 0, 0,   1, 0, 1, 0,   0, 1, 0, 1,   0, 0, 1, 0]).reshape((4, -1))
A = np.array([[ 10.,  -8.,   6.,  -3.,],
 [ 12., -10.,   8.,  -4.],
 [  1.,  -1.,   1.,   0.],
 [ -2.,   2.,  -2.,   2.]])
#A = np.array([[-1.,    -1.,    -1.   ],
# [-1.,     0.333, -1.   ],
# [-1.,    -1.,    -1.   ]])
print(A)


[[ 10.  -8.   6.  -3.]
 [ 12. -10.   8.  -4.]
 [  1.  -1.   1.   0.]
 [ -2.   2.  -2.   2.]]


In [3]:
%run drazin.py
A = np.array([[-1,1,2],[3,4,5],[6,7,8]])
is_drazin(A, la.inv(A), 0)

True

In [66]:
%run drazin.py
#A = np.array([-1,1,2,3,4,5,6,7,8]).reshape((3,3))
Ad = drazin_inverse(A)
k = index(A)

print(Ad)

[[ 2.  -1.5  1.  -0.5]
 [ 2.  -1.5  1.  -0.5]
 [-1.   1.  -1.   1. ]
 [-2.   2.  -2.   2. ]]


In [13]:
is_drazin(A, drazin_inverse(A), 4)

False

In [67]:
%run drazin.py
A = np.array([0, 1, 0, 0,   1, 0, 1, 0,   0, 1, 0, 1,   0, 0, 1, 0]).reshape((4, -1))

print(effective_resistance(A))

[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]]
