In [1]:
import numpy as np
from scipy import linalg as la

In [2]:
A = np.array([-1,1,2,3,4,5,6,7,8]).reshape((3,3))
#A = 2*np.array([0,1,1,0]).reshape((2,2))
A = np.array([0, 1, 1, 0]).reshape((2,2)) # line from a to b
A = np.array([0, 1, 1, 1, 0, 1, 1,1, 0]).reshape((3,3)) #connected triangle
A = np.array([0, 1, 0, 0,   1, 0, 1, 0,   0, 1, 0, 1,   0, 0, 1, 0]).reshape((4, -1))
print(A)


[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 0]]


In [3]:
%run drazin.py
A = np.array([[-1,1,2],[3,4,5],[6,7,8]])
is_drazin(A, la.inv(A), 0)

True

In [4]:
%run drazin.py
A = np.array([-1,1,2,3,4,5,6,7,8]).reshape((3,3))
Ad = drazin_inverse(A)
k = index(A)

print(drazin_inverse(A))

[[-1.          2.         -1.        ]
 [ 2.         -6.66666667  3.66666667]
 [-1.          4.33333333 -2.33333333]]


In [5]:
%run drazin.py
A = np.array([0, 1, 0, 0,   1, 0, 1, 0,   0, 1, 0, 1,   0, 0, 1, 0]).reshape((4, -1))

print(effective_resistance(A))

[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]]
